### ISSUE TITLE
aws restore from bucket1 to bucket2 issue

### ISSUE THREAD

**Issue by adlucio87** [marko-bast/aws-s3-glacier-restore#1]
Hi Marko,

I am trying using your Py script to restore some objects from mybucket and restore them on another bucket in the same region. 
I used this cmd:
python aws-s3-glacier-restore -p s3://mydrbucket1/1800002SNI/00000002.pdf -D s3://mydrbucket2

During the execution i received this error:
Starting restore using Bulk tier... Restoring s3://mydrbucket1/1800002SNI/00000002.pdf
Traceback (most recent call last):
  File "aws-s3-glacier-restore", line 316, in <module>
    args['status_print'])
  File "aws-s3-glacier-restore", line 236, in restore_main
    map(lambda x: {**dict(file=x), **restore_args}, to_restore))
  File "C:\Program Files\Python37\lib\multiprocessing\pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Program Files\Python37\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
  File "C:\Program Files\Python37\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Program Files\Python37\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "aws-s3-glacier-restore", line 123, in restore
    raise e
  File "aws-s3-glacier-restore", line 103, in restore
    'Tier': to_restore['tier']}})
  File "C:\Program Files\Python37\lib\site-packages\botocore\client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Program Files\Python37\lib\site-packages\botocore\client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (MalformedXML) when calling the RestoreObject operation: The XML you provided was not well-formed or did not validate against our published schema

Thank you for your help
Andrea

**Comment by marko-bast** [comment]
Hey Andrea,
Can you try specifying destination bucket without s3:// prefix so:
`python aws-s3-glacier-restore -p s3://mydrbucket1/1800002SNI/00000002.pdf -D mydrbucket2`

**Comment by adlucio87** [comment]
Hi Marko,
thanks for you replay, i have tried it but don't work.
I think is not supported yet from Aws.
have you used it? Suggestion for how can i resolve it?

**Comment by marko-bast** [comment]
I've used it before and restore to another bucket was working. Now I don't have access to test it again.

**Comment by cfurst** [comment]
I think the `OutputDestination` option is only for `select` restore requests and not for S3 file restore requests. Its supposed to be where the job outputs the results of the select query executed against the Glacier files. Why these types of requests were lumped together this like this, I don't know, but I think if you want to copy the restored file to somewhere else you will have to do it manually.

**Comment by marko-bast** [comment]
Seems like restore to a different bucket is not supported.
